# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogFlagObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_x', models.FloatField(default=0, editable=False)),
                ('a_y', models.FloatField(default=0, editable=False)),
                ('a_moved', models.BooleanField(default=False, editable=False)),
                ('a_img_width', models.FloatField(default=0, editable=False)),
                ('a_img_height', models.FloatField(default=0, editable=False)),
                ('a_width', models.FloatField(verbose_name='Width')),
                ('a_height', models.FloatField(verbose_name='Height')),
                ('a_color', models.CharField(default='#FFFFFF', max_length=8, verbose_name='Color')),
                ('a_rotation', models.IntegerField(default=0, verbose_name='Rotation')),
                ('a_name', models.CharField(default='Element', max_length=200, verbose_name='Name')),
                ('a_query', models.CharField(default='', max_length=150, verbose_name='Path (query to be done into Miniserver)')),
                ('a_value', models.FloatField(editable=False, null=True)),
                ('a_image', models.ImageField(default='', upload_to='images', verbose_name='Image FLAG')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalogObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_x', models.FloatField(default=0, editable=False)),
                ('a_y', models.FloatField(default=0, editable=False)),
                ('a_moved', models.BooleanField(default=False, editable=False)),
                ('a_img_width', models.FloatField(default=0, editable=False)),
                ('a_img_height', models.FloatField(default=0, editable=False)),
                ('a_width', models.FloatField(verbose_name='Width')),
                ('a_height', models.FloatField(verbose_name='Height')),
                ('a_color', models.CharField(default='#FFFFFF', max_length=8, verbose_name='Color')),
                ('a_rotation', models.IntegerField(default=0, verbose_name='Rotation')),
                ('a_name', models.CharField(default='Element', max_length=200, verbose_name='Name')),
                ('a_query', models.CharField(default='', max_length=150, verbose_name='Path (query to be done into Miniserver)')),
                ('a_value', models.FloatField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BooleanObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_x', models.FloatField(default=0, editable=False)),
                ('a_y', models.FloatField(default=0, editable=False)),
                ('a_moved', models.BooleanField(default=False, editable=False)),
                ('a_img_width', models.FloatField(default=0, editable=False)),
                ('a_img_height', models.FloatField(default=0, editable=False)),
                ('a_width', models.FloatField(verbose_name='Width')),
                ('a_height', models.FloatField(verbose_name='Height')),
                ('a_color', models.CharField(default='#FFFFFF', max_length=8, verbose_name='Color')),
                ('a_rotation', models.IntegerField(default=0, verbose_name='Rotation')),
                ('a_name', models.CharField(default='Element', max_length=200, verbose_name='Name')),
                ('a_query', models.CharField(default='', max_length=150, verbose_name='Path (query to be done into Miniserver)')),
                ('a_value', models.NullBooleanField(editable=False)),
                ('a_image_on', models.ImageField(default='', upload_to='images', verbose_name='Image ON')),
                ('a_image_off', models.ImageField(default='', upload_to='images', verbose_name='Image OFF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MiniServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(default='', max_length=100, verbose_name='Nom')),
                ('a_path', models.CharField(default='', max_length=100, verbose_name='Url del miniserver')),
                ('a_user', models.CharField(default='', max_length=50, verbose_name='Usuari administrador')),
                ('a_password', models.CharField(default='', max_length=50, verbose_name='Password per usuari')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(default='', max_length=100, verbose_name='Nom')),
                ('a_image', models.ImageField(default='', upload_to='images', verbose_name='Planol')),
                ('a_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bttviewer.MiniServer', verbose_name='Miniserver')),
            ],
        ),
        migrations.CreateModel(
            name='Valve3WaysObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_x', models.FloatField(default=0, editable=False)),
                ('a_y', models.FloatField(default=0, editable=False)),
                ('a_moved', models.BooleanField(default=False, editable=False)),
                ('a_img_width', models.FloatField(default=0, editable=False)),
                ('a_img_height', models.FloatField(default=0, editable=False)),
                ('a_width', models.FloatField(verbose_name='Width')),
                ('a_height', models.FloatField(verbose_name='Height')),
                ('a_color', models.CharField(default='#FFFFFF', max_length=8, verbose_name='Color')),
                ('a_rotation', models.IntegerField(default=0, verbose_name='Rotation')),
                ('a_name', models.CharField(default='Element', max_length=200, verbose_name='Name')),
                ('a_query', models.CharField(default='', max_length=150, verbose_name='Path (query to be done into Miniserver)')),
                ('a_value', models.FloatField(editable=False, null=True)),
                ('a_as_boolean', models.NullBooleanField(editable=False)),
                ('a_image_a', models.ImageField(default='', upload_to='images', verbose_name='Image (A -> AB) / (ON)')),
                ('a_image_b', models.ImageField(default='', upload_to='images', verbose_name='Image (B -> AB) / (OFF)')),
                ('a_image_ab', models.ImageField(default='', upload_to='images', verbose_name='Image A+B -> AB')),
                ('a_plane', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bttviewer.Plane', verbose_name='Plane relation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booleanobject',
            name='a_plane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bttviewer.Plane', verbose_name='Plane relation'),
        ),
        migrations.AddField(
            model_name='analogobject',
            name='a_plane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bttviewer.Plane', verbose_name='Plane relation'),
        ),
        migrations.AddField(
            model_name='analogflagobject',
            name='a_plane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bttviewer.Plane', verbose_name='Plane relation'),
        ),
    ]
